name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ModuleBuilder
        shell: pwsh
        run: |
          Install-Module -Name ModuleBuilder -Force
        
      - name: Build Module
        shell: pwsh
        run: |
          . ./build.ps1
     
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Rtc.GitHub
          path: build/Rct.GitHub/
